import { GoogleGenAI } from '@google/genai';
import { ENV } from '../utils/env.js';

// Google Cloud TTS (Node.js)
import textToSpeech from '@google-cloud/text-to-speech';

type CommercialInput = {
  businessName: string;
  businessType: string;
  offer: string;
  extraInfo?: string;
};

type CommercialContent = {
  headline: string;
  script: string;
};

function requireApiKey(): string {
  // Your env.ts defines API_KEY (not GEMINI_API_KEY)
  if (!ENV.API_KEY) throw new Error('Missing ENV.API_KEY');
  return ENV.API_KEY;
}

const ai = new GoogleGenAI({ apiKey: requireApiKey() });

// ---- Core: generate ad copy ----
export async function generateCommercialContent(input: CommercialInput): Promise<CommercialContent> {
  const prompt = `
Create a short, punchy YouTube CTV commercial concept for a local business.

Business Name: ${input.businessName}
Business Type: ${input.businessType}
Offer: ${input.offer}
Extra Info: ${input.extraInfo ?? ''}

Return JSON only in this exact shape:
{
  "headline": "MAX 8 WORDS, BIG, TV-STYLE",
  "script": "45-60 second voiceover script. Friendly, confident, local. End with a clear CTA to scan QR code."
}
`;

  const resp = await ai.models.generateContent({
    model: 'gemini-2.0-flash',
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
  });

  const text = resp.text ?? '';
  // Try to parse JSON safely (Gemini sometimes wraps in markdown)
  const jsonText = text
    .replace(/```json/gi, '')
    .replace(/```/g, '')
    .trim();

  let parsed: any;
  try {
    parsed = JSON.parse(jsonText);
  } catch {
    // fallback minimal
    return {
      headline: `${input.businessType} SPECIAL`,
      script: `Hi! This is a quick message from ${input.businessName}. Right now: ${input.offer}. Scan the QR code to learn more and claim it today.`,
    };
  }

  return {
    headline: String(parsed.headline ?? '').slice(0, 60) || `${input.businessType} SPECIAL`,
    script:
      String(parsed.script ?? '') ||
      `Hi! This is a quick message from ${input.businessName}. ${input.offer}. Scan the QR code to learn more.`,
  };
}

// ---- Optional helpers used by routes.ts ----
export async function generateBackgroundImage(_headline: string, _businessType: string): Promise<string> {
  // For now return an empty base64 placeholder (you can swap to Imagen later)
  // Must return base64 (without data: prefix) because routes.ts expects base64 string.
  return '';
}

/**
 * Generates REAL voiceover audio as MP3 and returns base64 (no data: prefix).
 *
 * Requires Cloud Run service account to have Text-to-Speech permissions:
 * roles/texttospeech.user (or broader).
 *
 * Uses Application Default Credentials (ADC) automatically on Cloud Run.
 */
export async function generateVoiceover(script: string): Promise<string> {
  const clean = (script || '').trim();
  if (!clean) return '';

  // Cloud Run ADC will be used automatically if the service account has permissions.
  const client = new textToSpeech.TextToSpeechClient();

  const request = {
    input: { text: clean },
    // Pick a good default English voice. Change as desired.
    voice: {
      languageCode: 'en-US',
      name: 'en-US-Neural2-D',
    },
    audioConfig: {
      audioEncoding: 'MP3' as const,
      speakingRate: 1.0,
    },
  };

  const [response] = await client.synthesizeSpeech(request);

  const audioContent = response.audioContent;
  if (!audioContent) return '';

  // audioContent can be Buffer, Uint8Array, or string depending on lib versions
  const buf = Buffer.isBuffer(audioContent) ? audioContent : Buffer.from(audioContent as any);

  return buf.toString('base64');
}

export async function generateYoutubeMetadata(
  businessName: string,
  offer: string
): Promise<{ title: string; description: string; tags: string[] }> {
  const title = `${businessName} | ${offer}`.slice(0, 95);
  const description = `Unlisted commercial preview for ${businessName}. Offer: ${offer}\n\nGenerated by Easy TV Offers.`;
  return {
    title,
    description,
    tags: ['local business', 'commercial', 'YouTube CTV', 'Easy TV Offers'],
  };
}
