import { GoogleGenAI } from '@google/genai';
import { ENV } from '../utils/env.js';

type CommercialInput = {
  businessName: string;
  businessType: string;
  offer: string;
  extraInfo?: string;
};

type CommercialContent = {
  headline: string;
  script: string;
};

function requireApiKey(): string {
  if (!ENV.API_KEY) throw new Error('Missing ENV.API_KEY');
  return ENV.API_KEY;
}

const ai = new GoogleGenAI({ apiKey: requireApiKey() });

/**
 * Generate headline + script using Gemini
 */
export async function generateCommercialContent(
  input: CommercialInput
): Promise<CommercialContent> {
  const prompt = `
Create a short, punchy YouTube CTV commercial concept for a local business.

Business Name: ${input.businessName}
Business Type: ${input.businessType}
Offer: ${input.offer}
Extra Info: ${input.extraInfo ?? ''}

Return JSON only in this exact shape:
{
  "headline": "MAX 8 WORDS, BIG, TV-STYLE",
  "script": "45-60 second voiceover script. Friendly, confident, local. End with a clear CTA to scan QR code."
}
`;

  const resp = await ai.models.generateContent({
    model: 'gemini-2.0-flash',
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
  });

  const text = resp.text ?? '';

  const jsonText = text
    .replace(/```json/gi, '')
    .replace(/```/g, '')
    .trim();

  try {
    const parsed = JSON.parse(jsonText);
    return {
      headline: String(parsed.headline ?? '').slice(0, 60) || `${input.businessType} SPECIAL`,
      script:
        String(parsed.script ?? '') ||
        `Hi! This is a quick message from ${input.businessName}. ${input.offer}. Scan the QR code to learn more.`,
    };
  } catch {
    return {
      headline: `${input.businessType} SPECIAL`,
      script: `Hi! This is a quick message from ${input.businessName}. Right now: ${input.offer}. Scan the QR code to learn more and claim it today.`,
    };
  }
}

/**
 * TEMP background image generator
 * Returns a NON-EMPTY base64 PNG so bg.png is never 0 bytes
 * (We will upgrade this to a real AI image next)
 */
export async function generateBackgroundImage(
  _headline: string,
  _businessType: string
): Promise<string> {
  // 1x1 white PNG (base64)
  return "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO5p9m8AAAAASUVORK5CYII=";
}

/**
 * TEMP voice generator
 * Returns NON-EMPTY base64 PCM audio (3 seconds of silence)
 * (We will upgrade this to real TTS next)
 */
export async function generateVoiceover(_script: string): Promise<string> {
  const sampleRate = 24000;
  const seconds = 3;
  const bytesPerSample = 2;

  const byteLength = sampleRate * seconds * bytesPerSample;
  const pcm = Buffer.alloc(byteLength); // silent audio

  return pcm.toString('base64');
}

/**
 * YouTube metadata helper
 */
export async function generateYoutubeMetadata(
  businessName: string,
  offer: string
): Promise<{ title: string; description: string; tags: string[] }> {
  const title = `${businessName} | ${offer}`.slice(0, 95);
  const description = `Unlisted commercial preview for ${businessName}. Offer: ${offer}

Generated by Easy TV Offers.`;

  return {
    title,
    description,
    tags: ['local business', 'commercial', 'YouTube CTV', 'Easy TV Offers'],
  };
}
